sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
      - python2.6
install:
  - pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible
  - pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
  - pip install -r requirements.txt

script:
  - python2.7 -m compileall -fq .
  - ansible-validate-modules --exclude 'test*' ./
  - ansible-playbook --connection=local -i '127.0.0.1' -M cloud/amazon -vvvv test/integrations/site.yml -C
  - nosetests --with-coverage

after_success:  
  - coveralls 
  - codecov
